### ISSUE TITLE
Change default dispatcher and make it configurable

### ISSUE THREAD

**Issue by ktoso** [kciesielski/reactive-kafka#1]
Since the underlying kafka calls can be blocking as I understand the code the actors should use a dedicated either PinnedDispatcher or they should share a ThreadPool (probably better here). The library should provide the actors prepped with some 'reactive-kafka.default-dispatcher` or something similar. 

Here's some docs: http://doc.akka.io/docs/akka/snapshot/scala/dispatchers.html

**Comment by kciesielski** [comment]
Fixed by #2
